[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "fa7c6222eede5c3655bdc712b00061bfd8df86d8"
os = "macos"

    [[WrapIt.download]]
    sha256 = "a1b1431c2bfc004b9968d99aa773e1d468f4b2e92fb30ed68120018893508fb3"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ade9e4bbaa7b61dca420e052740a17c6b1a712ba"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "0bffd7403820c73fa1bdfb6243f4d1449df41fdfca9cda0ddd7660fcdef50aba"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "707fcff65e95300c4f74968c9510846e8f53fb63"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "dd8512a77787e99de0ecf3fff922ca0a34ed85c88f886441284c54079f22936c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29bdb30ba5cdeb43d3cc840bb3ed98d786794c36"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2e100a2f7bac2f53494719baddb7672c49c7df3857791cca5ad14491aac23d50"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19ede9cfa33ae13fadbd1853ad07ce26cb6031c5"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "97011c4906b457eaf0c7bdbb539c40a82c48efd15657793bb7210aca25388e65"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18b283a1bd1030572cad23f96177ca8e5ed59d64"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "3a8bfa1d227691fc0bcc19804daf95c63cf42d2f5439f6543a4ad394ff89a2ea"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d13db83b0b84f709a911c6336d995e4ed4ea98e"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "3b0392e97fc5f850f124131946681f9179ce75d0e3edd6fd926cf2ae48512e73"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c30f62f4f309a5d576f3ac306515460b5ca24b5d"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "e8eabaf07f80818ba2abdd307d934ef672c041be85bd995c379fb53b8c81cd80"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e965b54232ef3d0f8a4f7a37790832a670b5b139"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "422ca5bb6aeebd2ce6999966f3743516bfbb3e156d9f6e93f59d573bf6d485ea"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14c254ec556e53add006334a1b8768fba3c43960"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "390b962270ac4f3ec72e5187a2451508f979dc0bb21ffdab91c849cc42b7d8df"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33da6049824f9aa7ea3ada3bf3565164a931f679"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "3164d8427b7579959dc081ddb2acc1ebf66048309b783033a481bc1340f45147"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4474be4de0e69023a9ac4cc9443d62a2e1f8af98"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "4535151ad48a134ade8476f2c8c97ffb755c87ce29cba8de1b570af2b43b5a0b"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7276bbdf408ef6190d09510f4a20ec9222a13bde"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "8d420e8f9e36facc252bead08cb2c71d77cdf9eb737f534cf207fbbfa46da0d8"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab6b59a76c7922a963e38a9f124f2fdd5d023c54"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "3d3903e6500419142c9bcddfde8e080b7c899bfe8efd04b550151686c0630c67"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.i686-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08574bee3cf5aaf5871401c9577eff03b612ff60"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "145ed5621c390d1c9bc988f80daa5678d3ec5b4af4ed7f528545b0f2bbdcca61"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.i686-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "853f5afd0f961ff854cca9e8d085dcb13d657340"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "c82a96cd494e057b8450cafd567479925b7be94f1584be6b22fb66dbc8428851"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeb355866b840f29fea7c144a6920301221e2b94"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "69d75b3218baae345c665d12ea798512f8f604003cdf5d9542728f1a18d3092e"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "ab23951efff66e5c5ea3f0cbd25a0bdfe01eb7ae"
os = "macos"

    [[WrapIt.download]]
    sha256 = "58e792d27f9a72a17eb295dfd7af4a94d748433ee8d2c3d91711bd9e7ef2a481"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.x86_64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a6170141e06221105b96f8595de4626dc502bc"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "752b0dfc19694175b09fdd36a38aaf3095b92a649c1acbfd5f86addc774553d3"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31c63a37488fad39ba6928ed215cbcea8a33c922"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "b1ef0a0c0fc2c3faa69b83249e5b7984bf81976ae89b3d43837419299d2fc372"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "837649e642c75a8a1e3624d90c9d8dd4b5c53baf"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "d1884df68ea618c090973ac313f41f94ff3fe11ea12a11f8f5161de6228508a8"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8328760594db8637bcb8022d18ab960afd43cbad"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "26cd809bbd8b01c6858f55b9e183dcd86f0fa28b114be138f883b3ddb14e6e0b"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "c513ebd7ed3b4b78b89ce865449f84b73550d3b7"
os = "freebsd"

    [[WrapIt.download]]
    sha256 = "6a141b27fe2fa6146c536e09bb8429e9d09cb56a129fc4088c04c616e2da5b6a"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.2+0/WrapIt.v1.3.2.x86_64-unknown-freebsd.tar.gz"
