[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "0a3e85087c7306fe12d3c98dd4b1805e0d6cd83c"
os = "macos"

    [[WrapIt.download]]
    sha256 = "19142a7ed7a3316a065760bb815cf9fb9638938b7bd255dce49ea5e13daaf9c1"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc6dcc8b41dfffc656340b6cbe5f06686b94d1f4"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "b213e1fd6b1b8e00d6f696798b17898473daa3c8b25ec7fee10006586f415fd6"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "744b95834fa44e79fba9753bddf97d0d95796f6d"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "776b7e1414abc898873a805749c3321e9f78d5cd951905955fcccec44822a97a"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5a1a30bad1361e1a5420340283cca936e26b9bf"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "3ef4031ab8658a7608dc440a7cc3b487e9a20108082010b1bddbde60ab9c1439"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acdf7c22cba446660d09c921f2d979d72c3b805f"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2025c0c5cea763ea363461a87dd9eec4097070e58530ecd82096cc4bc462c643"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3299f5252ccb7f42ceab74a771b1c8dd1848e9a3"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "6b1b2901893cb28c77c4e2771c0307349bc12a177b51759b293b69d95f0d998d"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "472ffeee144a2189fccd7c7c14297f11ef30a82d"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "bf90b52783e10b33b3124d6d8bc91146f6c5599890ac31035bdf6d510bad2e59"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "598b34184e57bee5b5b6df87dfcecca2b6b63ea7"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "38a276fb048d871400a9ddc73a521f9edb2236ead775cd93b7cb1c3eadbc4ad4"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3adb098951d831e90d6d70d673a5dc0c5ef9085c"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "8eba57b0083d6cec6b0de2fbbb36577907c747e06c0e27e7421fd0ffde0813bf"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f79783416f3b97c67b044537abf8ef8a7f418448"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "f2c5a7a2b90d875e1b84e815b14b0ca2b81d36d2441ba92c54db7adb25328517"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af9671fdf1e1d44f15b316ec5fcc492253523e98"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "c79658892bd43f44df6daa1cce3ffa86c7d6ec13e9c70281e32d1f34c32ca792"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6337dcb5e08dc2a01a0641af8b387ea6325a742"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "337fe96c5b747abc8f66810b0003e1c3dfb46cd6bd24a85eee9863169770cb93"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6f283eb683714585d2dc92f3ebc2a1015818fdd"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "7eda47febc845c18c04e4307417f24391429db2f5cc63121becd86f596167d72"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0097e4a233d43b23045c6888cee78f63d2fd311"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2b78a20913e7f4a66a3511998765371a89d8b3344576a2dc18b8bf6b1b2d24b9"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.i686-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e428f510279fd76e54355ee8b18e0b8ba662962f"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "9b93211a718896b09b251d098d1184081848e42c22d774278eda66de730743a0"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.i686-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1da5edf78ec4ffcd8bf660fedc4a0c479ffc58b3"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "3c85bfa2d4d31dc4874e91d24e5e4c57a21e8a0510781e5b61fb00668bdc0e4c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b4865abccd6a0da747b52b5765d40269180a7e9"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "e6bbb8401ae44d2692ca0f2caf6ac1b2ddccdbd81679b814c89e2bfe4782830f"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "279ef3cf928b51f6e9c1432cda808d6675b68974"
os = "macos"

    [[WrapIt.download]]
    sha256 = "99712ba61a0e82b9ad97cb1d42de86e0c40fce84d1794f10e5cb3ea9ab2ca026"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.x86_64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3cbe882198e9fd99cd457cb085dcc04b884aa6c2"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "1261a93afad19c9b7558e458a71de5315776bdc334314efd3fcec507e8507944"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63a32f986cd4e59f895e11ec59860ec014c19288"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2985e3c4f63db2cb84f1236542ac139c4adda16fb235dacf848dca8d9c55998c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f10e99cbd46248fb374d2ed58eb1d85bc0301d4c"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "4842fd347a4108c8537fc3b07db07a32367c0529dcb658a23c770c724537d9dd"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17c467869e325091124fd9e9bdc02ecb060915f9"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "d38894549a1abe0ea39355d332e4cfc6d39d489b4fcb877be0fa220a32e4b006"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "f584ff9b3082fc30a53a008e9f995963edf86f32"
os = "freebsd"

    [[WrapIt.download]]
    sha256 = "0064701ee5b0a9d6b01a6f97024f220e95e44aaebf0aa9b6135df521cb6b6cbf"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.4.0+0/WrapIt.v1.4.0.x86_64-unknown-freebsd.tar.gz"
