[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "13936abf10ba3eb0cfa9db301e6df7ee224a05b5"
os = "macos"

    [[WrapIt.download]]
    sha256 = "84a0b024233f3168a21a45234edf3acdec0fb88b7bebff8d36b89eff32991db3"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b3abde6b71a6b16f2e7eccb08f54a998fcbc208"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "9edf9e2a3bd45d7d1423a33b803773b25380e5c9323b6676cd8d66a2d14fd109"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.aarch64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3c3767c761fdd4c78c49e991fbeaca90e0cab43"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "154218c14756d9668a912e2559ce3047cf0540655f41d9d31d437d9f28d569a0"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0a179d0c51fd56388417e4f1211320c1470515e"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "b3dbb9c866cf3bde6f7170bf85fbccc8ef97a0084fb3f24309b039e598105138"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.aarch64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06871a5965660860785879fb4c4ae1c4465f6048"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "261c9ab89a2790cda167189c0da4ef0beaf6a78fe263a245f6fe2e4560bbe075"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.aarch64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40823bd01b541ac1005b9bf3b088147c0ceddb32"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "d11d26ca55824c48d61c858f7a698b852e58920aa2e466114c5c5ae93e74c83d"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9f84d3401344512b501205a344ae9bf0d182693"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "661cbb50963ba71d34af95eae54349ab1c127a6db699bf678379bccf89da72d5"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e7dc56f5f661b9c5b1d8709473632bbd4b789a8"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "6f0da14e4f90ba0bb5272a644b0ca60c027674065b8db7981b40f24c1cf7bcbf"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e401914a0521b7008fb07a67e070826e8428661"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2243b11638b7239d7ad669bbb6f448c737205ed32e562f6f0ded179bfe9d5b1c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6dbcbe80afb999dbfc4c3616fa9831ec1b18a7ec"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "65716e95cc9ee8d503ff2862edfe37a5a4cbdc93d9e81bd61dd12030b911ebc4"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "544ee7480d20bc33d3e606de357322a7062736e0"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "d230d07541f52f160a93301acb2dc96647d811fc228e097e40a10d17ff88ebcd"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87de3b27362de1ff4fccd252c0e4ce9694a7fac6"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "942970115835cfe9d6cf485c0b658c929c73525911d1c936eb9219d2ac77294c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a55c62191f282259fe7595dacfc41397bff85c1"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "0ad1d72aa4393ec1b4115d39911050f4f4b5c9ea558f94a5c9a429a3c7302566"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72a7daa1e29a356b2357a0af182adbb6d67ab725"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "51a55eebcaeda5afbdd84f07bb88b44c8ab5b4cef7ff1f241dac992c7ae21c30"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.i686-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4215b7aa6823341cc3e0564ffd5971f39797005c"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "57fe9a9753bd9d1db1e87e1d8ee9e121f1764d80c0022ea23e623d9d8135b22d"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.i686-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b615391064b7d55e17fda5d55a7c7d67b9e1d751"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2820bc6a0c130421fc173af1dc0a2514c8eef98e96dd0762e4ddd979fb2085e3"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09e0308eb012ed745845fdd73b35d3d986b13a1c"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "4ced7d43a294eae72f206d39d5f0e508654391869a2c7ab8e00fd4bbf13888bd"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "90d2a114a35cd69078078be0fe353925c9162c48"
os = "macos"

    [[WrapIt.download]]
    sha256 = "d2f68a48cdd8b9570a1ddea44f6596343aafac65fc6cb04d1225b3c5e8296003"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.x86_64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f90cc3d992a476650fb92c3d94d806394255ff3c"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "34b2a78d6fe0c386c7c52bb09605d0d425c5146a56aa073f0aa02c8fd56ed821"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.x86_64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d973917a325e2886fda498adc99176768d9774d9"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2d267601f70991053ddde60e811a7a1a56ce8579ffc213e74c3473ab984e7e31"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.x86_64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca88ecf37883d66d747c24228567a38baa3e6aad"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "014774d79c96e6b339921f5adf90f8bcf7c796f6e39c9ec807a8473f2972a373"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.x86_64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "445ff7293b0b3e6cbd91c4cb7876c0707def1f36"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "f7f8c1aded172849711a9991022ed65828603e875819c1e8a41e57883ee1264f"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.x86_64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "d8a15b34425c2710e1d031bc5c08dd6ed692e5de"
os = "freebsd"

    [[WrapIt.download]]
    sha256 = "3806393b40c5139109194b1d0d34fbe0748c1fbe0e3e6cfb707f0334f2c809dd"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.3+0/WrapIt.v1.3.3.x86_64-unknown-freebsd.tar.gz"
