[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "daeb65431b51d0a9d5c424565acdc674d1db7d80"
os = "macos"

    [[WrapIt.download]]
    sha256 = "1ec76281c354f49707fb2f5ac4cb17a486b3fccac83b706b4712bde4bc5aeba6"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "c2c775d3ace1d0aacd5375665473b4e7803eed0e"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "aa28c578eb39713e4358839d0e50266325c66be79085e3bc0397f6108a12973d"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.aarch64-linux-gnu.tar.gz"
[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "62d5b20448fcebcedea2ea107efc3778871ec8e8"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "661e4c840022412d49f4b448b64fa0be5bb4aa8fc5f34b762635ee5ca20b8185"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.aarch64-linux-musl.tar.gz"
[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "6f0cb5fc0b1bdc20cc561e57ea304045f3c87388"
os = "freebsd"

    [[WrapIt.download]]
    sha256 = "08881c01f5f1ffbbebadc7eb0daa3d0f471fffdd839e6b8bd048541876612f94"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.aarch64-unknown-freebsd.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "def2b1e2dd6218a3f4dd626ada28a0ccf87b568e"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "a35d99c1b2a9e173de55e774e2740a1cbfadb03807deeafb5b36870840566577"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99fa1bb0fad715580abf1e393194e4f1265a71ff"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "85d53bab0245655e2b8465223cf5d55c9b46abe8c50cb6e9217d9db136e8fc47"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36f8046bc17e8cf2a65b09b72264798c6f03de7c"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "7abafc174f5606da3b3c7a7a8c450c5f75c1eff42400af51869ec5491e020bd3"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8fd4c6299a23ef2d9c2309a88fb61f1d6ca81003"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "e29e7231329037b13c64ab4696efe9ea988086854a64fb68120c16ee96ff6d0b"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[WrapIt]]
arch = "i686"
git-tree-sha1 = "9c11c7d0dd429fdf441be03bc6d44bc7e5b9eb6e"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "6f636120000cdee6502b4afe9f30a660a9ff2832397a259f3ed43ac9b2d492e7"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.i686-linux-gnu.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
git-tree-sha1 = "5b53ae8ae6b7df45fd6a5043fcf7d05c27dc5f73"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "49bc5e3f844c22a25b449763160df448d36e570431486de66befc003550d783b"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[WrapIt]]
arch = "riscv64"
git-tree-sha1 = "8a32b04887917656779b6213de917bc8abf6965b"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "375799daeef0ed9ea276724af078a2076572e699bf8352faf757902beb360bd9"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.riscv64-linux-gnu.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "bbde3c8cabb959365613c4c0fbbccbdb93c8e96f"
os = "macos"

    [[WrapIt.download]]
    sha256 = "5a27a7bcc91a48610214828687bed2aef89b123073389970710545a8d184b35e"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.x86_64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "6893eb845b0c93ba0e86a6c5d4a9a4b7bb12a912"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "b632f35d4cb58156795c563955862e7da5d7e1f8b2bcc5a5b43aa6796ce21e76"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.x86_64-linux-gnu.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "6622d9982b329020be8b79fd96af027de7bf2ac4"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "e88dfae5407fac8c568cb22f7c23e475dab0a23d842cc24b17824e7535c5987c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.x86_64-linux-musl.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "53bf41f97185de4537db0e40240ca3b6cdbff7b9"
os = "freebsd"

    [[WrapIt.download]]
    sha256 = "47ff8acc9a0c5265284033c76093040810b130d369e1b68b9cc8c4a00325747a"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.x86_64-unknown-freebsd.tar.gz"
