[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "c474be2dade28c2738212c5ce9132085cf6f8505"
os = "macos"

    [[WrapIt.download]]
    sha256 = "bb48cbc47d112472b2ae6228774a7ec24d50e9b823d61a471697fd83556e9d72"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1f48e4abad6dd6deb6d8a51f1c1f6c50f71ec7a"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "503b9a98595dec4509852e6fc2641bc4b24f2f0663be7d708662472c0538a13d"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a388b3eb5518ca95d0faad0c439439ec309adf64"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "6c230a0eef875a2e3eddd1a8f8904e90e1d2107e9e508dae94d43789f094960c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eecc07df6b492d5a7ab34e5c6d88621196ff6560"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "2b4fcf928aaeedb4300dd44bebd75c6b928fd65eaf1331f1d01f9a569933048c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c96aeb65be34e741f34b9a642befa20c22afc866"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "30cb51bb2ebc1c6102c473dce58fb32cdeb66e258f72fce450d5df07cee6523f"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5d39d29e75d9503cf0a1a7f5b6cdf4ffaa7dc82"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "c787fff8b9e6c14a9cd6039b1091787698efd2f42e49fe4436781c26ff4d39d1"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55ac32ac9a6dbb8658b35bb730470acf721cdc5a"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "8d2ad153c05be730ba1a7d0cebe77822390422f7749807fcb8b109235f990014"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5781bbd9adae1c344a348aa1430704db0ee37d2b"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "1d08515fd1e7e4b221c59117ecc3ca8b103dee8150e3dbe0b24362374f70f103"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afcb03c7d24a52f6cd8c239e8ce1d83a0527561e"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "d6fce8666e4a5b7425ab5e63068e5947e060f0e491df7ae22f1a0cad33ee2e4e"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f288deb80b6ede829e575c4d0862eb01e4c3c44"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "0dc10257b82dc8c2bb30b44abd64aee58230f4928b8c51e7d93ce8510a735edc"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd62ca0b93379532a99383b0841bc3a5a7c29b50"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "779f83942f30f76ede3c48c812f30d128f927cb5bbe6e12d334a6d2f6a53ba45"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d600785f006a7f7eef8965b8b7e21fe9912d7fa7"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "e29ce81698a6a4b3ebdbba651119d2de429cb8e275ac4330e63b0c73cdd2ebc7"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[WrapIt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1deb18bdea6a6be5da57563b86a4a39372725ac"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "bd14739c4cd14fb59ba4ad9e6562fd7a81a7b6db9904faa27a6fb0eab81e92d7"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "262b51147754b38fd543bae8193a8ac49ec66671"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "bc90cee8b23f1550cd991abdcaf2d74a4a3289e9e3683cc200e1fd5096e42634"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.i686-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "612d0b2e7aa9ca27393388b62d55805b423c02e9"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "86d8cae11fa1cb3a454a3b67427d300123d1c39d37d2944af83035260d2cb97d"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.i686-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "555eb7da6c655fe7ea9229a1aeabfc2e513d16f0"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "90e64a3a762eb7c5cc84aa13d825ae7f2559cff129f42a0383de46f7492c450c"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "136f01e4727aed5a675e58c350d76ca543b3db8d"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "5c1e0931498bf20e95196f687f6aef49e4f474c74a607d1d913adfba9b02cd1f"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "3ae3140b0103d68e03d648777b5d1eae3bc1467f"
os = "macos"

    [[WrapIt.download]]
    sha256 = "68bbc8126e2024f556d15d832bd87fed65ec027300ce33d4dd8212ed6fa74dc2"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.x86_64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b577a5bc588446dcf434c1a15f8574d70b9a875"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "8fef460f5e5a3f8bd52d45dcc67bf0f37eeba87612fb444681b061419772edbb"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fb825c9c8e8d9550e376fb588dbcc072e3a056f"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "bfd064c467f92640e18dbfc1d462c10c49f7a071472392e47742e38888ec65fe"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "691abf7343b95bebb3710a7489f225373e501d11"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "677c550cd83203701171c8a4abafdbcc4c5fba9db97580773c476a9562696163"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5390dfc5c5b7a08216581a700e16e0aa9aa4df29"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "4b1630fe64c777ecf92195066eef3bf0160904be5cd04c6b91098be87ddc77a8"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "7fbeff8be18340fe3e1ff6660cd34657ab70ac0b"
os = "freebsd"

    [[WrapIt.download]]
    sha256 = "16407fe772f3640491cda9d421d60ffe2a714d9a45a9a0281d87b09e323ca316"
    url = "https://github.com/JuliaBinaryWrappers/WrapIt_jll.jl/releases/download/WrapIt-v1.3.1+0/WrapIt.v1.3.1.x86_64-unknown-freebsd.tar.gz"
